
#' Produce IPEDS HR Part A2
#'
#' @description  Part A2 --- Count of FT instructional staff by tenure status, medical school, and function
#'
#' @param df a dataframe
#' @param output a string (\code{"part"}, \code{"full"}, or \code{"both"})
#'
#' @return a txt file
#' @export
#' @importFrom dplyr bind_rows filter select bind_rows group_by summarize ungroup arrange transmute
#' @importFrom rlang .data
#'
make_hr_part_A2 <- function(df, output = 'part') {

  #set up the grid of options
  combos_A2 <- expand.grid(Unitid = get_ipeds_unitid(df),
                           Tenure = c(1:7),
                           IsMedical = c(0:1),
                           InstFunction = c(1:3, 5),  #4 is generated by the system (subtotal of 1:3)
                           Count = 0)

  #produce the uploadable format
  partA2 <- df %>%
            dplyr::filter(.data$CurrentEmployee == 1,
                   .data$Instructional == 1, #instructional
                   .data$FtPt == 'F') %>%
            dplyr::select(.data$Unitid, .data$Tenure, .data$IsMedical, .data$InstFunction, .data$Count) %>%
            #add extra combinations
            dplyr::bind_rows(combos_A2) %>%
            #aggregate the full data
            dplyr::group_by(.data$Unitid, .data$Tenure, .data$IsMedical, .data$InstFunction) %>%
            dplyr::summarize(Count = sum(.data$Count)) %>%
            dplyr::ungroup() %>%
            #sort for easy viewing
            dplyr::arrange(.data$Tenure, .data$IsMedical, .data$InstFunction) %>%
            #format for upload
            dplyr::transmute(UNITID = paste0("UNITID=", .data$Unitid),
                   SURVSECT = "SURVSECT=HR1",
                   PART = "PART=A2",
                   TENURE = paste0("TENURE=", .data$Tenure),
                   ISMEDICAL = paste0("ISMEDICAL=", .data$IsMedical),
                   INSTFUNCTION = paste0("INSTFUNCTION=", .data$InstFunction),
                   COUNT = paste0("COUNT=", .data$Count))

  write_report(df = partA2,
               component = 'HumanResources',
               part = "PartA2",
               output = output)
}
